<?php

/**
 * @var \TresdTech\FinalProject\Block\crud $block
 */

echo $block->crud();

?>

<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}
a{
  margin-top: 30px;
}
</style>

<table>
  <tr>
    <th class="post-name">First Name</th>
    <th class="post-name">Last Name</th>
    <th>Email</th>
    <th>Telephone</th>

  </tr>
    <?php
        foreach ($block->getPostCollection() as $key=>$post){
            if(isset($post)){
              echo '<tr>
              <td>'.$post->getFirst_name().'</td>
              <td>'.$post->getLast_name().'</td>
              <td>'.$post->getEmail().'</td>
              <td>'.$post->getTelephone().'</td>
              </tr>';
        }else{
          echo "No hay registros <br>";
        }
          
             
        }
        
    ?>
</table>
<form>
<a class="action submit primary" href="<?php echo $block->getUrl('finalproject/index/form');?>" role="button">FORM</a>
</form>
</body>
</html>