<?php

/**
 * @var \TresdTech\FinalProject\Block\crud $block
 */

echo $block->crud();

?>

<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>

<table>
  <tr>
    <th class="post-name">First Name</th>
    <th class="post-name">Last Name</th>
    <th>Email</th>
    <th>Telephone</th>

  </tr>
    <?php
        foreach ($block->getPostCollection() as $key=>$post){
            echo '<tr>
                    <td>'.$post->getFirst_name().'</td>
                    <td>'.$post->getLast_name().'</td>
                    <td>'.$post->getEmail().'</td>
                    <td>'.$post->getTelephone().'</td>
                  </tr>';
        }
    ?>
</table>
<form action="http://192.168.0.25/finalproject/index/Form">
    <input type="submit" value="Go to Form" />
</form>
</body>
</html>