<?php

/**
 * @var \TresdTech\FinalProject\Block\crud $block
 */

echo $block->crud();

?>

<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}
.btn{
  margin-top: 30px;
}
</style>

<table>
  <tr>
    <th class="post-name">First Name</th>
    <th class="post-name">Last Name</th>
    <th>Email</th>
    <th>Telephone</th>

  </tr>
    <?php

                $DataCollection = $block->getPostCollection(); 
                if (!count($DataCollection)) {
                echo '<h1>NO HAY DATOS</h1>';
              }
        foreach ($block->getPostCollection() as $key=>$post){
              echo '<tr>
              <td>'.$post->getFirst_name().'</td>
              <td>'.$post->getLast_name().'</td>
              <td>'.$post->getEmail().'</td>
              <td>'.$post->getTelephone().'</td>
              </tr>';          
            } 
    ?>
</table>
<form>
<a class="btn action submit primary" href="<?php echo $block->getUrl('finalproject/index/form');?>" role="button">FORM</a>
</form>
</body>
</html>